# Generated by Django 5.2.17 on 2026-09-15 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(blank=True, max_length=160)),
                ("website", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=40)),
                (
                    "annual_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("employee_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("prospect", "Prospect"),
                            ("customer", "Customer"),
                            ("archived", "Archived"),
                        ],
                        default="prospect",
                        max_length=20,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("tags", models.ManyToManyField(blank=True, to="common.tag")),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization", "name"],
                        name="companies_c_organiz_cc0a6a_idx",
                    ),
                    models.Index(
                        fields=["organization", "status"],
                        name="companies_c_organiz_042678_idx",
                    ),
                ],
                "unique_together": {("organization", "name")},
            },
        ),
    ]
